package br.unb.cic.android.specs

import br.unb.cic.android.AndroidTaintBenchTest

trait ChuliaSpec extends FlowdroidSpec {
//  URL https://github.com/TaintBench/roidsec/blob/master/README.md
  override val sourceList = List(
    "<java.lang.String: byte[] getBytes(java.lang.String)>",
    "<android.location.Location: double getLatitude()>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<android.location.LocationManager: android.location.Location getLastKnownLocation(java.lang.String)>",
    "<java.io.ByteArrayOutputStream: byte[] toByteArray()>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<java.util.Date: long getTime()>",
    "<android.view.MotionEvent: int getAction()>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<android.content.ComponentName: java.lang.String getClassName()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<android.view.MotionEvent: float getY()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<android.content.res.Resources: android.content.res.AssetManager getAssets()>",
    "<android.location.LocationManager: java.lang.String getBestProvider(android.location.Criteria,boolean)>",
    "<android.database.Cursor: long getLong(int)>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<android.app.ActivityManager: java.util.List getRunningServices(int)>",
    "<java.io.FileInputStream: void <init>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<android.widget.Scroller: int getCurrY()>",
    "<android.os.Bundle: java.lang.String getString(java.lang.String)>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<java.io.RandomAccessFile: java.nio.channels.FileChannel getChannel()>",
    "<java.io.File: void <init>",
    "<java.lang.String: byte[] getBytes()>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getActiveNetworkInfo()>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<java.util.Vector: java.lang.Object get(int)>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<android.view.MotionEvent: float getX()>",
    "<android.database.Cursor: int getInt(int)>",
    "<android.graphics.Bitmap: android.graphics.Bitmap createBitmap(int,int,android.graphics.Bitmap$Config)>",
    "<android.location.Location: double getLongitude()>",
    "<android.widget.Scroller: int getCurrX()>",
  )

  override val sinkList = List(
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<org.apache.http.impl.client.DefaultHttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<java.lang.String: java.lang.String substring(int,int)>",
    "<android.view.Window: void setFlags(int,int)>",
    "<android.location.Criteria: void setBearingRequired(boolean)>",
    "<android.util.Log: int i(java.lang.String,java.lang.String)>",
    "<android.graphics.ColorMatrix: void set(float[])>",
    "<android.location.LocationManager: void requestLocationUpdates(java.lang.String,long,float,android.location.LocationListener)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<android.app.ActivityManager: java.util.List getRunningServices(int)>",
    "<android.location.Criteria: void setAccuracy(int)>",
    "<java.io.OutputStream: void write(byte[],int,int)>",
    "<android.graphics.drawable.GradientDrawable: void setGradientType(int)>",
    "<android.graphics.Paint: void setStyle(android.graphics.Paint$Style)>",
    "<java.io.OutputStream: void write(byte[])>",
    "<android.content.IntentFilter: void setPriority(int)>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<android.location.Criteria: void setAltitudeRequired(boolean)>",
    "<android.graphics.Paint: android.graphics.ColorFilter setColorFilter(android.graphics.ColorFilter)>",
    "<android.graphics.Paint: void setTextAlign(android.graphics.Paint$Align)>",
    "<java.io.FileOutputStream: void <init>",
    "<android.location.Criteria: void setPowerRequirement(int)>",
    "<java.io.RandomAccessFile: void write(byte[],int,int)>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<android.location.Criteria: void setCostAllowed(boolean)>",
    "<android.os.Bundle: void putString(java.lang.String,java.lang.String)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<android.content.Intent: android.content.Intent putExtras(android.os.Bundle)>",
    "<android.graphics.Matrix: void setValues(float[])>",
  )
}