package br.unb.cic.android.specs

import br.unb.cic.android.AndroidTaintBenchTest

trait FakeappstoreSpec extends AndroidTaintBenchTest {
//  URL https://github.com/TaintBench/fakeappstore/blob/master/README.md
  override val sourceList = List(
    "<javax.crypto.SecretKeyFactory: javax.crypto.SecretKeyFactory getInstance(java.lang.String)>",
    "<android.telephony.SmsManager: android.telephony.SmsManager getDefault()>",
    "<android.content.Intent: java.lang.String getStringExtra(java.lang.String)>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<javax.crypto.Cipher: byte[] doFinal(byte[])>",
    "<android.util.Xml: org.xmlpull.v1.XmlPullParser newPullParser()>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.app.Activity: android.view.View getCurrentFocus()>",
    "<android.view.View: android.os.IBinder getWindowToken()>",
    "<android.content.res.Resources: java.lang.String getString(int)>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<android.content.ComponentName: java.lang.String getClassName()>",
    "<android.os.Environment: java.io.File getExternalStorageDirectory()>",
    "<java.net.HttpURLConnection: int getResponseCode()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<java.lang.Integer: int parseInt(java.lang.String,int)>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<org.apache.http.HttpEntity: java.io.InputStream getContent()>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<android.app.admin.DevicePolicyManager: boolean isAdminActive(android.content.ComponentName)>",
    "<android.media.RingtoneManager: android.net.Uri getDefaultUri(int)>",
    "<android.app.ActivityManager: java.util.List getRunningServices(int)>",
    "<java.io.FileInputStream: void <init>",
    "<javax.crypto.Cipher: javax.crypto.Cipher getInstance(java.lang.String)>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<android.os.Environment: java.lang.String getExternalStorageState()>",
    "<android.content.pm.PackageManager: java.util.List getInstalledPackages(int)>",
    "<android.content.Intent: int getIntExtra(java.lang.String,int)>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<java.io.File: java.lang.String getAbsolutePath()>",
    "<java.io.File: void <init>",
    "<java.lang.String: byte[] getBytes()>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<android.view.View: int getId()>",
    "<android.telephony.TelephonyManager: java.lang.String getLine1Number()>",
    "<android.content.Intent: java.io.Serializable getSerializableExtra(java.lang.String)>",
    "<android.app.Activity: java.lang.Object getSystemService(java.lang.String)>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getNetworkOperatorName()>",
    "<android.content.Intent: java.lang.String getDataString()>",
    "<org.json.JSONArray: java.lang.Object get(int)>",
    "<android.media.RingtoneManager: android.media.Ringtone getRingtone(android.content.Context,android.net.Uri)>",
  )

  override val sinkList = List(
    "<android.app.ProgressDialog: void setMax(int)>",
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.os.Handler: boolean sendMessage(android.os.Message)>",
    "<java.io.FileOutputStream: void write(byte[],int,int)>",
    "<java.lang.String: java.lang.String substring(int,int)>",
    "<android.util.Log: int i(java.lang.String,java.lang.String)>",
    "<android.content.Intent: android.content.Intent setFlags(int)>",
    "<java.lang.Integer: int parseInt(java.lang.String,int)>",
    "<android.widget.Toast: android.widget.Toast makeText(android.content.Context,java.lang.CharSequence,int)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<android.app.ActivityManager: java.util.List getRunningServices(int)>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.io.Serializable)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,android.os.Parcelable)>",
    "<android.app.ProgressDialog: void setMessage(java.lang.CharSequence)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<android.util.Log: int v(java.lang.String,java.lang.String)>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.io.FileOutputStream: void <init>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<android.app.ProgressDialog: void setProgress(int)>",
    "<org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,int)>",
    "<android.app.ProgressDialog: void setProgressStyle(int)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
  )
}