package br.unb.cic.android.specs

import br.unb.cic.android.FlowdroidSpec

trait FakebankAndroidSampSpec extends FlowdroidSpec {
//  URL https://github.com/TaintBench/fakebank_android_samp/blob/master/README.md
  override val sourceList = List(
    "<org.json.JSONObject: int getInt(java.lang.String)>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<java.io.ByteArrayOutputStream: byte[] toByteArray()>",
    "<android.telephony.SmsMessage: long getTimestampMillis()>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<java.util.Date: long getTime()>",
    "<java.net.InetAddress: java.net.InetAddress getByName(java.lang.String)>",
    "<java.net.URL: java.lang.String getPath()>",
    "<java.net.URL: java.lang.String getHost()>",
    "<java.text.DateFormat: java.lang.String format(java.util.Date)>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<android.content.res.Resources: android.content.res.AssetManager getAssets()>",
    "<java.lang.reflect.Field: java.lang.Object get(java.lang.Object)>",
    "<java.io.FileInputStream: void <init>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<android.os.Bundle: java.lang.String getString(java.lang.String)>",
    "<java.lang.String: byte[] getBytes()>",
    "<android.telephony.TelephonyManager: java.lang.String getSimOperatorName()>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getActiveNetworkInfo()>",
    "<java.lang.Class: java.lang.reflect.Field[] getDeclaredFields()>",
    "<android.view.View: int getId()>",
    "<android.telephony.TelephonyManager: java.lang.String getLine1Number()>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.telephony.TelephonyManager: java.lang.String getSubscriberId()>",
    "<com.example.bankmanager.BankActivity: android.view.View findViewById(int)>",
    "<java.io.BufferedReader: java.lang.String readLine()>",
    "<java.lang.String: byte[] getBytes(java.lang.String)>",
    "<android.net.NetworkInfo: android.net.NetworkInfo$State getState()>",
    "<java.lang.Runtime: java.lang.Runtime getRuntime()>",
    "<android.view.MotionEvent: int getAction()>",
    "<java.lang.Class: java.lang.String getName()>",
    "<android.content.Intent: android.content.Intent setClass(android.content.Context,java.lang.Class)>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<java.net.HttpURLConnection: int getResponseCode()>",
    "<android.os.Environment: java.io.File getExternalStorageDirectory()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<java.net.Socket: java.io.OutputStream getOutputStream()>",
    "<java.net.Socket: java.io.InputStream getInputStream()>",
    "<org.apache.http.HttpEntity: java.io.InputStream getContent()>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<java.lang.Thread: java.lang.Thread$UncaughtExceptionHandler getDefaultUncaughtExceptionHandler()>",
    "<java.net.URL: int getPort()>",
    "<android.widget.EditText: android.text.Editable getText()>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<android.os.Environment: java.lang.String getExternalStorageState()>",
    "<android.telephony.TelephonyManager: java.lang.String getSimSerialNumber()>",
    "<java.io.File: void <init>",
    "<java.io.File: java.lang.String getAbsolutePath()>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<java.lang.Throwable: java.lang.Throwable getCause()>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.lang.reflect.Field: java.lang.String getName()>",
    "<android.telephony.SmsMessage: java.lang.String getDisplayMessageBody()>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<android.os.PowerManager: android.os.PowerManager$WakeLock newWakeLock(int,java.lang.String)>",
    "<android.database.Cursor: int getInt(int)>",
    "<android.net.NetworkInfo: java.lang.String getTypeName()>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
  )

  override val sinkList = List(
    "<com.example.service.InstallService: void startActivity(android.content.Intent)>",
    "<java.lang.String: boolean startsWith(java.lang.String)>",
    "<android.util.Log: int e(java.lang.String,java.lang.String,java.lang.Throwable)>",
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.os.Handler: boolean sendMessage(android.os.Message)>",
    "<java.io.FileOutputStream: void write(byte[],int,int)>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.Integer)>",
    "<org.apache.http.impl.client.DefaultHttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<android.content.Intent: android.content.Intent setClass(android.content.Context,java.lang.Class)>",
    "<java.lang.Thread: void setDefaultUncaughtExceptionHandler(java.lang.Thread$UncaughtExceptionHandler)>",
    "<java.lang.String: java.lang.String substring(int,int)>",
    "<android.util.Log: int i(java.lang.String,java.lang.String)>",
    "<android.util.Log: int d(java.lang.String,java.lang.String)>",
    "<android.widget.Toast: android.widget.Toast makeText(android.content.Context,java.lang.CharSequence,int)>",
    "<java.io.DataOutputStream: void flush()>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<java.io.DataOutputStream: void write(byte[])>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.String)>",
    "<java.io.OutputStream: void write(byte[],int,int)>",
    "<android.app.ProgressDialog: void setMessage(java.lang.CharSequence)>",
    "<android.widget.TextView: void setText(java.lang.CharSequence)>",
    "<android.app.ProgressDialog: void setIndeterminate(boolean)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>",
    "<android.widget.RadioGroup: void setOnCheckedChangeListener(android.widget.RadioGroup$OnCheckedChangeListener)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<java.io.OutputStream: void write(byte[])>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<java.io.FileOutputStream: void <init>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.io.FileOutputStream: void write(byte[])>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.os.AsyncTask: void onPostExecute(java.lang.Object)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<java.net.HttpURLConnection: java.io.OutputStream getOutputStream()>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.Long)>",
    "<android.util.Log: int e(java.lang.String,java.lang.String)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
  )
}