package br.unb.cic.android.specs

import br.unb.cic.android.AndroidTaintBenchTest

trait SmsGoogleSpec extends AndroidTaintBenchTest {
//  URL https://github.com/TaintBench/sms_google/blob/master/README.md
  override val sourceList = List(
    "<android.telephony.SmsManager: android.telephony.SmsManager getDefault()>",
    "<org.json.JSONObject: int getInt(java.lang.String)>",
    "<android.content.Intent: java.lang.String getStringExtra(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<java.util.Date: long getTime()>",
    "<java.lang.Class: java.lang.String getName()>",
    "<org.json.JSONObject: org.json.JSONObject getJSONObject(java.lang.String)>",
    "<android.os.Environment: java.io.File getExternalStoragePublicDirectory(java.lang.String)>",
    "<java.lang.Boolean: boolean parseBoolean(java.lang.String)>",
    "<android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<android.app.admin.DevicePolicyManager: boolean isAdminActive(android.content.ComponentName)>",
    "<android.widget.ProgressBar: int getProgress()>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<java.io.File: boolean delete()>",
    "<android.telephony.TelephonyManager: java.lang.String getNetworkCountryIso()>",
    "<org.json.JSONObject: java.lang.String getString(java.lang.String)>",
    "<android.graphics.Color: int parseColor(java.lang.String)>",
    "<org.json.JSONObject: boolean getBoolean(java.lang.String)>",
    "<java.io.File: void <init>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<java.util.Calendar: java.util.Calendar getInstance()>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getActiveNetworkInfo()>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<android.telephony.SmsMessage: java.lang.String getDisplayOriginatingAddress()>",
    "<android.telephony.TelephonyManager: java.lang.String getLine1Number()>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<android.os.PowerManager: android.os.PowerManager$WakeLock newWakeLock(int,java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getNetworkOperatorName()>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
    "<com.google.elements.Utils: java.lang.String getDeviceId()>",
    "<org.json.JSONObject: org.json.JSONArray getJSONArray(java.lang.String)>",
    "<org.json.JSONArray: org.json.JSONObject getJSONObject(int)>",
    "<java.util.Calendar: int get(int)>",
  )

  override val sinkList = List(
    "<android.widget.TextView: void setTextColor(int)>",
    "<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>",
    "<org.apache.http.params.HttpConnectionParams: void setConnectionTimeout(org.apache.http.params.HttpParams,int)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.content.Intent: android.content.Intent setPackage(java.lang.String)>",
    "<java.io.FileOutputStream: void write(byte[],int,int)>",
    "<java.lang.Boolean: boolean parseBoolean(java.lang.String)>",
    "<android.util.Log: int d(java.lang.String,java.lang.String)>",
    "<android.util.Log: int i(java.lang.String,java.lang.String)>",
    "<android.content.Intent: android.content.Intent setFlags(int)>",
    "<org.apache.http.params.HttpConnectionParams: void setSoTimeout(org.apache.http.params.HttpParams,int)>",
    "<android.content.Intent: android.content.Intent setClassName(android.content.Context,java.lang.String)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<android.app.AlarmManager: void set(int,long,android.app.PendingIntent)>",
    "<java.net.HttpURLConnection: void connect()>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,android.os.Parcelable)>",
    "<java.io.File: boolean delete()>",
    "<android.widget.TextView: void setText(java.lang.CharSequence)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>",
    "<android.graphics.Color: int parseColor(java.lang.String)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<android.util.Log: int v(java.lang.String,java.lang.String)>",
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,java.lang.Object)>",
    "<android.content.res.AssetManager: java.io.InputStream open(java.lang.String)>",
    "<java.io.FileOutputStream: void <init>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<android.util.Log: int e(java.lang.String,java.lang.String)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
    "<java.lang.Class: java.lang.Class forName(java.lang.String)>",
  )
}