package br.unb.cic.android.specs

import br.unb.cic.android.FlowdroidSpec

trait SmssendPackageInstallerSpec extends FlowdroidSpec {
//  URL https://github.com/TaintBench/smssend_packageInstaller/blob/master/README.md
  override val sourceList = List(
    "<org.json.JSONObject: int getInt(java.lang.String)>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<org.json.JSONArray: java.lang.String getString(int)>",
    "<javax.net.ssl.SSLContext: javax.net.ssl.SSLContext getInstance(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<org.json.JSONObject: org.json.JSONObject getJSONObject(java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<java.lang.reflect.Field: java.lang.Object get(java.lang.Object)>",
    "<android.webkit.WebView: void loadUrl(java.lang.String)>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getNetworkInfo(int)>",
    "<org.json.JSONObject: java.lang.String getString(java.lang.String)>",
    "<android.content.pm.PackageManager: java.util.List getInstalledPackages(int)>",
    "<org.json.JSONObject: boolean getBoolean(java.lang.String)>",
    "<java.lang.Class: java.io.InputStream getResourceAsStream(java.lang.String)>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<java.security.MessageDigest: java.security.MessageDigest getInstance(java.lang.String)>",
    "<java.lang.String: byte[] getBytes()>",
    "<java.lang.Class: java.lang.Class[] getClasses()>",
    "<android.telephony.TelephonyManager: java.lang.String getLine1Number()>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<org.json.JSONObject: long getLong(java.lang.String)>",
    "<java.security.MessageDigest: byte[] digest()>",
    "<android.telephony.TelephonyManager: java.lang.String getSubscriberId()>",
    "<android.telephony.SmsManager: android.telephony.SmsManager getDefault()>",
    "<java.lang.String: byte[] getBytes(java.lang.String)>",
    "<java.io.BufferedReader: java.lang.String readLine()>",
    "<org.apache.http.conn.scheme.PlainSocketFactory: org.apache.http.conn.scheme.PlainSocketFactory getSocketFactory()>",
    "<java.lang.Runtime: java.lang.Runtime getRuntime()>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>",
    "<java.net.HttpURLConnection: int getResponseCode()>",
    "<android.os.Environment: java.io.File getExternalStorageDirectory()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<java.security.KeyStore: void load(java.io.InputStream,char[])>",
    "<android.telephony.TelephonyManager: java.lang.String getSimCountryIso()>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<java.lang.Class: java.lang.String getCanonicalName()>",
    "<javax.net.ssl.SSLContext: javax.net.ssl.SSLSocketFactory getSocketFactory()>",
    "<org.apache.http.params.HttpConnectionParams: int getSoTimeout(org.apache.http.params.HttpParams)>",
    "<java.io.File: void <init>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.lang.Class: java.lang.reflect.Field getField(java.lang.String)>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<android.app.PendingIntent: android.app.PendingIntent getActivity(android.content.Context,int,android.content.Intent,int)>",
    "<java.util.Vector: java.lang.Object get(int)>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<java.security.KeyStore: java.security.KeyStore getInstance(java.lang.String)>",
    "<org.apache.http.params.HttpConnectionParams: int getConnectionTimeout(org.apache.http.params.HttpParams)>",
    "<android.webkit.WebView: android.webkit.WebSettings getSettings()>",
    "<org.json.JSONObject: org.json.JSONArray getJSONArray(java.lang.String)>",
    "<org.json.JSONArray: org.json.JSONObject getJSONObject(int)>",
  )

  override val sinkList = List(
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,int)>",
    "<android.content.Intent: android.content.Intent setData(android.net.Uri)>",
    "<java.lang.StringBuffer: void setLength(int)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<java.io.FileOutputStream: void write(byte[],int,int)>",
    "<java.lang.String: java.lang.String substring(int,int)>",
    "<android.webkit.WebView: void setScrollBarStyle(int)>",
    "<java.util.Vector: java.lang.Object set(int,java.lang.Object)>",
    "<android.webkit.WebView: void addJavascriptInterface(java.lang.Object,java.lang.String)>",
    "<org.apache.http.params.HttpProtocolParams: void setHttpElementCharset(org.apache.http.params.HttpParams,java.lang.String)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<java.io.DataOutputStream: void write(byte[])>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<android.app.Notification: void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)>",
    "<android.webkit.WebView: void setLayoutParams(android.view.ViewGroup$LayoutParams)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<android.webkit.WebSettings: void setJavaScriptEnabled(boolean)>",
    "<java.io.DataOutputStream: void writeBytes(java.lang.String)>",
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,java.lang.Object)>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<org.apache.http.params.HttpProtocolParams: void setContentCharset(org.apache.http.params.HttpParams,java.lang.String)>",
    "<java.lang.Class: java.lang.Class forName(java.lang.String)>",
    "<java.lang.String: boolean startsWith(java.lang.String)>",
    "<android.app.NotificationManager: void notify(int,android.app.Notification)>",
    "<org.apache.http.params.HttpConnectionParams: void setConnectionTimeout(org.apache.http.params.HttpParams,int)>",
    "<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>",
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<org.json.JSONObject: java.lang.String toString(int)>",
    "<org.apache.http.conn.ssl.SSLSocketFactory: void setHostnameVerifier(org.apache.http.conn.ssl.X509HostnameVerifier)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,boolean)>",
    "<android.content.Intent: android.content.Intent setFlags(int)>",
    "<java.io.DataOutputStream: void flush()>",
    "<android.app.AlarmManager: void set(int,long,android.app.PendingIntent)>",
    "<java.net.HttpURLConnection: void connect()>",
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,long)>",
    "<android.webkit.WebView: void setWebChromeClient(android.webkit.WebChromeClient)>",
    "<android.app.ProgressDialog: void setMessage(java.lang.CharSequence)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>",
    "<android.webkit.WebView: void setWebViewClient(android.webkit.WebViewClient)>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.io.FileOutputStream: void <init>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<java.net.HttpURLConnection: java.io.OutputStream getOutputStream()>",
    "<android.content.Intent: android.content.Intent putExtras(android.os.Bundle)>",
    "<org.apache.http.conn.scheme.SchemeRegistry: org.apache.http.conn.scheme.Scheme register(org.apache.http.conn.scheme.Scheme)>",
    "<android.app.ProgressDialog: void setProgressStyle(int)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
  )
}