package br.unb.cic.android.specs

import br.unb.cic.android.FlowdroidSpec

trait StelsFlashplayerAndroidUpdateSpec extends FlowdroidSpec {
//  URL https://github.com/TaintBench/stels_flashplayer_android_update/blob/master/README.md
  override val sourceList = List(
    "<android.telephony.SmsManager: android.telephony.SmsManager getDefault()>",
    "<org.json.JSONObject: int getInt(java.lang.String)>",
    "<java.io.BufferedReader: java.lang.String readLine()>",
    "<java.lang.String: byte[] getBytes(java.lang.String)>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<org.json.JSONArray: java.lang.String getString(int)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<org.json.JSONObject: org.json.JSONObject getJSONObject(java.lang.String)>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>",
    "<java.net.HttpURLConnection: int getResponseCode()>",
    "<android.os.Environment: java.io.File getExternalStorageDirectory()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<java.lang.reflect.Field: java.lang.Object get(java.lang.Object)>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<android.webkit.WebView: void loadUrl(java.lang.String)>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getNetworkInfo(int)>",
    "<org.json.JSONObject: java.lang.String getString(java.lang.String)>",
    "<java.lang.Class: java.lang.String getCanonicalName()>",
    "<android.content.pm.PackageManager: java.util.List getInstalledPackages(int)>",
    "<org.json.JSONObject: boolean getBoolean(java.lang.String)>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<java.lang.Class: java.io.InputStream getResourceAsStream(java.lang.String)>",
    "<java.io.File: void <init>",
    "<java.lang.String: byte[] getBytes()>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.lang.Class: java.lang.Class[] getClasses()>",
    "<java.lang.Class: java.lang.reflect.Field getField(java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getLine1Number()>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<android.app.PendingIntent: android.app.PendingIntent getActivity(android.content.Context,int,android.content.Intent,int)>",
    "<java.util.Vector: java.lang.Object get(int)>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getSubscriberId()>",
    "<android.webkit.WebView: android.webkit.WebSettings getSettings()>",
    "<org.json.JSONObject: org.json.JSONArray getJSONArray(java.lang.String)>",
    "<org.json.JSONArray: org.json.JSONObject getJSONObject(int)>",
  )

  override val sinkList = List(
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,int)>",
    "<android.content.Intent: android.content.Intent setData(android.net.Uri)>",
    "<java.lang.String: boolean startsWith(java.lang.String)>",
    "<android.app.NotificationManager: void notify(int,android.app.Notification)>",
    "<java.lang.StringBuffer: void setLength(int)>",
    "<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>",
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<java.io.FileOutputStream: void write(byte[],int,int)>",
    "<android.webkit.WebView: void setScrollBarStyle(int)>",
    "<java.io.DataOutputStream: void flush()>",
    "<android.app.AlarmManager: void setRepeating(int,long,long,android.app.PendingIntent)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<java.io.DataOutputStream: void write(byte[])>",
    "<android.app.AlarmManager: void set(int,long,android.app.PendingIntent)>",
    "<java.net.HttpURLConnection: void connect()>",
    "<android.app.ProgressDialog: void setMessage(java.lang.CharSequence)>",
    "<android.app.Notification: void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)>",
    "<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<android.webkit.WebSettings: void setJavaScriptEnabled(boolean)>",
    "<java.io.DataOutputStream: void writeBytes(java.lang.String)>",
    "<android.webkit.WebView: void setWebViewClient(android.webkit.WebViewClient)>",
    "<org.json.JSONObject: org.json.JSONObject put(java.lang.String,java.lang.Object)>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<java.io.FileOutputStream: void <init>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<java.lang.Long: long parseLong(java.lang.String)>",
    "<java.lang.Integer: int parseInt(java.lang.String)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<java.net.HttpURLConnection: java.io.OutputStream getOutputStream()>",
    "<android.app.ProgressDialog: void setProgressStyle(int)>",
    "<android.content.Intent: android.content.Intent putExtras(android.os.Bundle)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
    "<java.lang.Class: java.lang.Class forName(java.lang.String)>",
  )
}