package br.unb.cic.android.specs

import br.unb.cic.android.FlowdroidSpec

trait TetusSpec extends FlowdroidSpec {
//  URL https://github.com/TaintBench/tetus/blob/master/README.md
  override val sourceList = List(
    "<android.telephony.SmsManager: android.telephony.SmsManager getDefault()>",
    "<java.io.BufferedReader: java.lang.String readLine()>",
    "<android.graphics.Bitmap: int getHeight()>",
    "<android.content.Intent: java.lang.String getStringExtra(java.lang.String)>",
    "<android.content.ContentResolver: android.database.Cursor query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String)>",
    "<android.database.sqlite.SQLiteDatabase: android.database.Cursor query(java.lang.String,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String,java.lang.String,java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.media.MediaPlayer: android.media.MediaPlayer create(android.content.Context,android.net.Uri)>",
    "<android.content.Context: java.io.FileInputStream openFileInput(java.lang.String)>",
    "<android.telephony.SmsMessage: java.lang.String getOriginatingAddress()>",
    "<android.content.Intent: android.content.Intent setClass(android.content.Context,java.lang.Class)>",
    "<android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>",
    "<java.net.HttpURLConnection: int getResponseCode()>",
    "<android.content.Intent: java.lang.String getAction()>",
    "<android.graphics.Bitmap: int getWidth()>",
    "<android.telephony.TelephonyManager: java.lang.String getDeviceId()>",
    "<android.telephony.SmsMessage: java.lang.String getMessageBody()>",
    "<android.telephony.TelephonyManager: java.lang.String getNetworkOperator()>",
    "<org.apache.http.HttpEntity: java.io.InputStream getContent()>",
    "<java.util.Locale: java.lang.String getCountry()>",
    "<android.database.Cursor: long getLong(int)>",
    "<android.telephony.SmsMessage: android.telephony.SmsMessage createFromPdu(byte[])>",
    "<android.graphics.Bitmap: android.graphics.Bitmap createBitmap(android.graphics.Bitmap,int,int,int,int,android.graphics.Matrix,boolean)>",
    "<android.webkit.WebView: void loadUrl(java.lang.String)>",
    "<android.content.Context: java.lang.Object getSystemService(java.lang.String)>",
    "<android.content.res.Resources: android.util.DisplayMetrics getDisplayMetrics()>",
    "<java.util.Locale: java.lang.String getLanguage()>",
    "<org.json.JSONObject: java.lang.String getString(java.lang.String)>",
    "<android.database.sqlite.SQLiteDatabase: android.database.Cursor query(java.lang.String,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String,java.lang.String,java.lang.String,java.lang.String)>",
    "<android.database.Cursor: java.lang.String getString(int)>",
    "<android.graphics.BitmapFactory: android.graphics.Bitmap decodeStream(java.io.InputStream)>",
    "<java.util.Locale: java.util.Locale getDefault()>",
    "<android.app.PendingIntent: android.app.PendingIntent getService(android.content.Context,int,android.content.Intent,int)>",
    "<java.util.HashMap: java.lang.Object get(java.lang.Object)>",
    "<android.net.ConnectivityManager: android.net.NetworkInfo getActiveNetworkInfo()>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<android.webkit.WebView: void loadData(java.lang.String,java.lang.String,java.lang.String)>",
    "<org.apache.http.HttpHost: java.lang.String getHostName()>",
    "<android.content.Intent: android.os.Bundle getExtras()>",
    "<android.os.Bundle: java.lang.Object get(java.lang.String)>",
    "<android.telephony.TelephonyManager: java.lang.String getNetworkOperatorName()>",
    "<org.apache.http.HttpHost: int getPort()>",
    "<android.database.Cursor: int getInt(int)>",
    "<android.content.Context: java.lang.String getString(int)>",
    "<java.util.LinkedList: java.lang.Object get(int)>",
  )

  override val sinkList = List(
    "<android.content.Intent: android.content.Intent setData(android.net.Uri)>",
    "<java.lang.String: boolean startsWith(java.lang.String)>",
    "<android.util.Log: int e(java.lang.String,java.lang.String,java.lang.Throwable)>",
    "<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>",
    "<android.content.Intent: android.content.Intent setAction(java.lang.String)>",
    "<android.net.Uri: android.net.Uri parse(java.lang.String)>",
    "<android.os.Handler: boolean sendMessage(android.os.Message)>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.Integer)>",
    "<android.content.Intent: android.content.Intent setClass(android.content.Context,java.lang.Class)>",
    "<java.lang.String: java.lang.String substring(int,int)>",
    "<java.io.OutputStreamWriter: void <init>",
    "<android.database.sqlite.SQLiteDatabase: long insert(java.lang.String,java.lang.String,android.content.ContentValues)>",
    "<android.util.Log: int w(java.lang.String,java.lang.String)>",
    "<android.util.Log: int i(java.lang.String,java.lang.String)>",
    "<android.util.Log: int d(java.lang.String,java.lang.String)>",
    "<android.media.MediaPlayer: void setOnPreparedListener(android.media.MediaPlayer$OnPreparedListener)>",
    "<android.widget.Toast: android.widget.Toast makeText(android.content.Context,java.lang.CharSequence,int)>",
    "<android.content.Context: android.content.ComponentName startService(android.content.Intent)>",
    "<java.io.OutputStreamWriter: void write(java.lang.String)>",
    "<android.content.Intent: android.content.Intent setDataAndType(android.net.Uri,java.lang.String)>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.String)>",
    "<android.app.AlarmManager: void set(int,long,android.app.PendingIntent)>",
    "<java.net.HttpURLConnection: void connect()>",
    "<android.util.Log: int w(java.lang.String,java.lang.String,java.lang.Throwable)>",
    "<android.app.ProgressDialog: void setMessage(java.lang.CharSequence)>",
    "<android.widget.ImageView: void setVisibility(int)>",
    "<java.net.URL: void <init>",
    "<java.net.URL: java.net.URLConnection openConnection()>",
    "<android.webkit.WebSettings: void setJavaScriptEnabled(boolean)>",
    "<java.net.HttpURLConnection: java.io.InputStream getInputStream()>",
    "<android.content.Context: void startActivity(android.content.Intent)>",
    "<android.database.sqlite.SQLiteDatabase: int update(java.lang.String,android.content.ContentValues,java.lang.String,java.lang.String[])>",
    "<java.net.HttpURLConnection: void setInstanceFollowRedirects(boolean)>",
    "<org.apache.http.client.HttpClient: org.apache.http.HttpResponse execute(org.apache.http.client.methods.HttpUriRequest)>",
    "<android.app.Activity: void onCreate(android.os.Bundle)>",
    "<android.app.Activity: boolean onKeyDown(int,android.view.KeyEvent)>",
    "<android.media.MediaPlayer: void setOnCompletionListener(android.media.MediaPlayer$OnCompletionListener)>",
    "<android.content.SharedPreferences$Editor: boolean commit()>",
    "<android.content.ContentValues: void put(java.lang.String,java.lang.Long)>",
    "<android.util.Log: int e(java.lang.String,java.lang.String)>",
    "<android.webkit.WebSettings: void setUserAgentString(java.lang.String)>",
    "<java.util.HashMap: java.lang.Object put(java.lang.Object,java.lang.Object)>",
    "<java.net.HttpURLConnection: void setRequestMethod(java.lang.String)>",
  )
}